import 'package:battle_royale/models/map_model.dart';

class Constants {
  static int get playerHealth => 100;
  static int get plusHealth => 10;
  static int get playerBulletCount => 10;
  static int get enemyDamage => 10;
  static List<String> get getImageList => [
        "bullets/5.png",
        // "enemys/1/0.png",
        // "enemys/1/1.png",
        // "enemys/1/2.png",
        // "enemys/1/3.png",
        // "enemys/1/4.png",
        // "enemys/1/5.png",
        // "enemys/1/6.png",
        // "enemys/1/7.png",
        // "enemys/1/8.png",
        // "enemys/1/9.png",
        // "enemys/1/10.png",
        // "enemys/1/11.png",
        // "enemys/2/0.png",
        // "enemys/2/1.png",
        // "enemys/2/2.png",
        // "enemys/2/3.png",
        // "enemys/2/4.png",
        // "enemys/2/5.png",
        // "enemys/2/6.png",
        // "enemys/2/7.png",
        // "enemys/2/8.png",
        // "enemys/2/9.png",
        // "enemys/2/10.png",
        // "enemys/2/11.png",
        // "enemys/3/0.png",
        // "enemys/3/1.png",
        // "enemys/3/2.png",
        // "enemys/3/3.png",
        // "enemys/3/4.png",
        // "enemys/3/5.png",
        // "enemys/3/6.png",
        // "enemys/3/7.png",
        // "enemys/3/8.png",
        // "enemys/3/9.png",
        // "enemys/3/10.png",
        // "enemys/3/11.png",
        // "players/0.png",
        // "layers/barn.png",
        // "layers/forest.png",
        // "layers/grass.png",
        // "layers/home.png",
        // "layers/stone.png",
        // "layers/water.png",
        // "utils/plus.png",
        // "players/boy/0.png",
        // "players/boy/1.png",
        // "players/boy/3.png",
        // "players/boy/4.png",
        // "players/boy/5.png",
        // "players/boy/6.png",
        // "players/boy/7.png",
        // "players/boy/8.png",
        // "players/boy/9.png",
        // "players/boy/10.png",
        // "players/boy/11.png",
        // "players/boy/13.png",
        // "players/boy/14.png",
        // "players/boy/dead/0.png",
        // "players/boy/dead/1.png",
        // "players/boy/dead/3.png",
        // "players/boy/dead/4.png",
        // "players/boy/dead/5.png",
        // "players/boy/dead/6.png",
        // "players/boy/dead/7.png",
        // "players/boy/dead/8.png",
        // "players/boy/dead/9.png",
        // "players/boy/dead/10.png",
        // "players/boy/dead/11.png",
        // "players/boy/dead/13.png",
        // "players/boy/dead/14.png",
        // "players/girl/0.png",
        // "players/girl/1.png",
        // "players/girl/2.png",
        // "players/girl/3.png",
        // "players/girl/4.png",
        // "players/girl/5.png",
        // "players/girl/6.png",
        // "players/girl/7.png",
        // "players/girl/8.png",
        // "players/girl/9.png",
        // "players/girl/10.png",
        // "players/girl/11.png",
        // "players/girl/13.png",
        // "players/girl/14.png",
        // "players/girl/15.png",
      ];

  static Map<String, Map<int, Map<String, String>>> get mapText => {
        "map.tmx": {
          100: {"title": "Heyy Beni Dinle", "text": "asdada"},
          70: {"title": "Heyy Patronn ", "text": "Daha dikkatli olmalıyız"},
          50: {"title": "HEYYYY", "text": "Zaman akıp gidiyor. Öldür şu kappeleri"},
          25: {"title": "Heyy Beni Dinle", "text": "asdada"},
        },
        "map2.tmx": {
          100: {"title": "Heyy Beni Dinle", "text": "Hadi yakalım şu prensesi"},
          70: {"title": "Heyy Beni Dinle", "text": "yapma be cok hasar aldık"},
          50: {"title": "Heyy Beni Dinle", "text": "ölüyoruz fuat abii"},
          20: {"title": "Heyy Beni Dinle", "text": "tükendik be"},
        }
      };
  static List<MapModel> get getMaps => [
        new MapModel("map", "barn", "Birinci Harita", false, isSelected: true),
        new MapModel("map2", "forest", "İkinci Harita", true),
      ];
}
